"""Git worktree management for isolated PR reviews.

Handles worktree creation, context file preparation (diff, changed_files, etc.),
dependency installation, and cleanup.
"""

import base64
import json
import logging
import os
import secrets
import shlex
import shutil
import subprocess
import time
from pathlib import Path

from gate.config import data_dir, load_config, repo_slug

logger = logging.getLogger(__name__)

# Patterns for Gate review/fix artifacts that must never be committed to the
# target repo.  Written to a per-worktree git exclude file by
# _setup_artifact_exclusions() so that `git add -A` ignores them.
#
# Keep in sync with GATE_ARTIFACT_FILES / GATE_ARTIFACT_GLOBS in gate/fixer.py.
GATE_EXCLUDE_PATTERNS = """\
# Gate review/fix artifacts — do not commit
# Auto-generated by workspace._setup_artifact_exclusions()
diff.txt
changed_files.txt
file_count.txt
diff_stats.txt
lines_changed.txt
pr-metadata.json
prior-review.json
build.json
triage.json
architecture.json
security.json
logic.json
verdict.json
fix-build.json
fix-diff.txt
fix-env.json
fix-resume-prompt.md
fix-rereview.json
no-codex.txt
fix.json
# Polish-loop / hopper-pipeline state files (PR #217 regression guard).
fix-polish.json
fix-decomposition.json
# Hopper-mode baseline marker written by fixer.ReviewFixer.run()
.gate/
*-findings.json
*-result.json
*-session-id.txt
*-raw.json
*.in.md
*.out.md
*.in.md.tmp
*.codex.log
gate-directions.md
postconditions.json
fix-build/
"""


def _b64_token(pat: str) -> str:
    return base64.b64encode(f"x-access-token:{pat}".encode()).decode()


def _git_env() -> dict[str, str]:
    """Build env for git commands with explicit HTTPS auth for private repos."""
    env = os.environ.copy()
    pat = os.environ.get("GATE_PAT", "")
    if pat:
        env["GIT_ASKPASS"] = "/bin/echo"
        env["GIT_TERMINAL_PROMPT"] = "0"
        env["GIT_CONFIG_COUNT"] = "1"
        env["GIT_CONFIG_KEY_0"] = "http.https://github.com/.extraheader"
        env["GIT_CONFIG_VALUE_0"] = f"Authorization: Basic {_b64_token(pat)}"
    return env


def _is_auto_fix_head(workspace: Path, bot_email: str) -> bool:
    """Return True iff HEAD in ``workspace`` was authored by the Gate bot.

    Used to distinguish a post-fix re-review (Gate reviewing its own
    auto-fix commit) from a normal human-authored PR push so the check
    status name can be labelled accordingly.

    Returns False on any subprocess error so the caller falls back to
    the normal ``gate-review`` name.
    """
    if not bot_email:
        return False
    try:
        result = subprocess.run(
            ["git", "show", "-s", "--format=%ae", "HEAD"],
            cwd=str(workspace),
            capture_output=True,
            text=True,
            timeout=10,
            check=True,
        )
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired, FileNotFoundError):
        return False
    return result.stdout.strip().lower() == bot_email.strip().lower()


class BranchNotFoundError(Exception):
    """Raised when the PR branch no longer exists on the remote.

    Typically means the PR was force-deleted/squash-merged between
    webhook receipt and our fetch. The orchestrator should treat this
    as a quiet skip (no crash, no fail-open approval spam).
    """


def _is_branch_not_found(stderr: str) -> bool:
    """Heuristic: does this git error indicate the branch is gone?

    Matches common forms from ``git fetch origin <branch>`` when the
    ref does not exist on the remote. Kept conservative so transient
    network errors ("Could not resolve host") don't get misclassified
    and swallow retries.
    """
    low = stderr.lower()
    return (
        "couldn't find remote ref" in low
        or "could not find remote ref" in low
        or "fatal: couldn't find remote ref" in low
    )


def _git_fetch_with_retry(
    repo_path: str, branch: str, max_retries: int = 4,
) -> None:
    """Fetch a branch with exponential backoff + recovery (Group 3A).

    - Exponential backoff (2s, 4s, 8s, 16s) instead of linear 5/10/15s
      — matches the rate limiter's typical back-pressure window.
    - Detects ``BranchNotFoundError`` explicitly so callers can skip
      reviewing a vanished branch instead of treating it as a generic
      fetch failure.
    - On the FIRST transient failure, runs ``git fetch --prune`` to
      evict stale local refs that can cause later fetches to race on
      ref advances (observed on PR 196 when a force-push invalidated
      the old ref).
    """
    env = _git_env()
    last_err: Exception | None = None
    for attempt in range(1, max_retries + 1):
        try:
            subprocess.run(
                ["git", "fetch", "origin", branch],
                cwd=repo_path,
                check=True,
                capture_output=True,
                timeout=90,
                env=env,
            )
            return
        except subprocess.CalledProcessError as e:
            stderr = (e.stderr or b"").decode("utf-8", errors="replace")
            if _is_branch_not_found(stderr):
                raise BranchNotFoundError(
                    f"branch {branch!r} not found on origin: {stderr.strip()}"
                ) from e
            last_err = e
            if attempt == 1:
                try:
                    subprocess.run(
                        ["git", "fetch", "--prune", "origin"],
                        cwd=repo_path, capture_output=True, timeout=90, env=env,
                    )
                except Exception as prune_err:
                    logger.info(f"git fetch --prune failed: {prune_err}")
            if attempt < max_retries:
                backoff = 2 ** attempt
                logger.warning(
                    f"git fetch retry {attempt}/{max_retries} in {backoff}s: "
                    f"{stderr.strip() or e}"
                )
                time.sleep(backoff)
                continue
            raise
        except subprocess.TimeoutExpired as e:
            last_err = e
            if attempt < max_retries:
                backoff = 2 ** attempt
                logger.warning(
                    f"git fetch timeout retry {attempt}/{max_retries} in {backoff}s"
                )
                time.sleep(backoff)
                continue
            raise
    if last_err:
        raise last_err


def _refresh_default_branch_ref(
    repo_path: str,
    default_branch: str,
    pr_branch: str,
    pr_number: int,
) -> None:
    """Refresh ``origin/<default_branch>`` so the review diff is computed
    against an up-to-date merge-base.

    ``prepare_context_files()`` builds the PR diff with
    ``git diff origin/<default_branch>...HEAD``. If ``origin/<default_branch>``
    has not been fetched recently, the triple-dot merge-base lags the remote
    and the diff pulls in every file that moved on the default branch between
    the stale cached ref and the real current merge-base. Small PRs end up
    with 30–50 phantom files in the review scope.

    This helper is a best-effort refresh called from :func:`create_worktree`.
    It **never raises** — the review can still proceed with whatever ref
    exists locally (that is today's behaviour), so widening the blast radius
    on a default-branch fetch failure would be a regression.

    Noop cases (fast path):
    - ``default_branch`` is falsy (misconfigured repo config).
    - ``default_branch`` equals ``pr_branch`` (rare: fork→base main→main PR).

    Retry budget is reduced to ``max_retries=2`` (default is 4) so the soft-
    fail worst case stays bounded at ~3 minutes rather than ~6.

    See openlawteam/gate Issue #15 (adin-chat PRs #217 and #220 repros).
    """
    if not default_branch or default_branch == pr_branch:
        return
    try:
        _git_fetch_with_retry(repo_path, default_branch, max_retries=2)
    except BranchNotFoundError as e:
        logger.warning(
            f"PR #{pr_number}: default branch {default_branch!r} not found "
            f"on origin; diff will be computed against whatever ref "
            f"exists locally ({e})"
        )
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as e:
        logger.warning(
            f"PR #{pr_number}: failed to refresh origin/{default_branch}; "
            f"diff may be computed against a stale ref: {e}"
        )


def _install_deps_with_retry(
    worktree_path: Path, cmd: str, max_retries: int = 2,
) -> None:
    """Run dependency install with retries (Group 3B).

    If the worktree vanishes during install — which happens when a
    re-push triggers ``cancel()`` and the old orchestrator's worktree
    is torn down by the single-teardown path — raise
    ``WorkspaceVanishedError`` so the orchestrator can treat it as a
    quiet cancel instead of a real install failure.
    """
    from gate.schemas import WorkspaceVanishedError

    env = os.environ.copy()
    env["npm_config_cache"] = str(data_dir() / "npm-cache")
    args = shlex.split(cmd)
    for attempt in range(1, max_retries + 1):
        if not worktree_path.exists():
            raise WorkspaceVanishedError(
                f"worktree {worktree_path} disappeared before install attempt {attempt}"
            )
        try:
            subprocess.run(
                args,
                cwd=str(worktree_path),
                check=True,
                capture_output=True,
                timeout=300,
                env=env,
            )
            return
        except FileNotFoundError as e:
            raise WorkspaceVanishedError(
                f"worktree {worktree_path} vanished during {cmd}: {e}"
            ) from e
        except (subprocess.TimeoutExpired, subprocess.CalledProcessError) as e:
            if not worktree_path.exists():
                raise WorkspaceVanishedError(
                    f"worktree {worktree_path} vanished during {cmd}"
                ) from e
            if attempt < max_retries:
                logger.warning(f"dep install retry {attempt}/{max_retries} ({cmd}): {e}")
                time.sleep(10)
                continue
            raise


def create_worktree(
    repo_path: str,
    pr_number: int,
    head_sha: str,
    branch: str,
    repo: str = "",
    config: dict | None = None,
) -> Path:
    """Create an isolated worktree for a PR review.

    Steps:
    1. git fetch origin <branch>
    2. git worktree add /tmp/gate-worktrees/pr<N>-<timestamp> <sha>
    3. Prepare context files (diff, changed_files, etc.)
    4. Run npm ci

    Args:
        repo_path: Path to the main repository clone.
        pr_number: PR number.
        head_sha: Head commit SHA to check out.
        branch: PR branch name.
        repo: GitHub owner/repo string for multi-repo support.
        config: Resolved config dict (avoids re-loading and ensures per-repo values).

    Returns:
        Path to the created worktree.
    """
    config = config or load_config()
    repo_cfg = config.get("repo", {})
    worktree_base = repo_cfg.get("worktree_base", "/tmp/gate-worktrees")
    # Use millisecond timestamp + random suffix to make path collisions
    # structurally impossible when two orchestrators start for the same
    # PR within the same second (can happen when a fix-push triggers the
    # GitHub webhook multiple times in quick succession).
    unique = f"{int(time.time() * 1000)}-{secrets.token_hex(3)}"
    slug = repo_slug(repo) if repo else ""
    if slug:
        worktree_path = Path(worktree_base) / f"{slug}-pr{pr_number}-{unique}"
    else:
        worktree_path = Path(worktree_base) / f"pr{pr_number}-{unique}"

    resolved_repo = str(Path(repo_path).expanduser())

    # Fetch the PR branch with explicit auth and retry
    logger.info(f"Fetching branch {branch} for PR #{pr_number}")
    _git_fetch_with_retry(resolved_repo, branch)

    # Issue #15: keep origin/<default_branch> fresh so prepare_context_files()
    # below does not build the PR diff against a stale merge-base. Best-effort
    # refresh — never raises, so a transient default-branch fetch failure
    # does not block the review.
    _refresh_default_branch_ref(
        resolved_repo,
        repo_cfg.get("default_branch", "main"),
        branch,
        pr_number,
    )

    # Create worktree at the specific SHA (also needs auth env for private repos)
    logger.info(f"Creating worktree at {worktree_path}")
    subprocess.run(
        ["git", "worktree", "add", str(worktree_path), head_sha],
        cwd=resolved_repo,
        check=True,
        capture_output=True,
        timeout=30,
        env=_git_env(),
    )

    # Checkout the PR branch so git push works (worktree add creates detached HEAD)
    subprocess.run(
        ["git", "checkout", "-B", branch, "HEAD"],
        cwd=str(worktree_path),
        check=True,
        capture_output=True,
        timeout=10,
    )

    # Set bot identity for fix pipeline commits
    bot = repo_cfg.get("bot_account", "gate-bot")
    for key, val in [("user.name", bot), ("user.email", f"{bot}@users.noreply.github.com")]:
        subprocess.run(
            ["git", "config", key, val],
            cwd=str(worktree_path),
            capture_output=True,
            timeout=10,
        )

    # Remove .claude/ from worktree so Claude inherits trust from parent
    claude_dir = worktree_path / ".claude"
    if claude_dir.is_dir():
        shutil.rmtree(claude_dir, ignore_errors=True)

    # Pre-trust the worktree path in Claude's config
    _trust_directory(worktree_path)

    # Prevent Gate artifacts from being staged by git add -A
    _setup_artifact_exclusions(resolved_repo, worktree_path)

    prepare_context_files(worktree_path, config=config)

    # Install dependencies using profile
    from gate import profiles

    profile = profiles.resolve_profile(repo_cfg, worktree_path)
    dep_cmd = profile.get("dep_install_cmd", "")
    if dep_cmd:
        logger.info(f"Installing dependencies: {dep_cmd}")
        _install_deps_with_retry(worktree_path, dep_cmd)
    else:
        logger.info(f"No dep install command for {worktree_path}, skipping")

    return worktree_path


def _trust_directory(directory: Path) -> None:
    """Register a directory as trusted in Claude Code's config.

    Claude Code stores per-project trust in ~/.claude.json under
    projects.<path>.hasTrustDialogAccepted. Without this, Claude
    shows an interactive "trust this folder" prompt that blocks
    automated agent stages.
    """
    claude_json = Path.home() / ".claude.json"
    try:
        if claude_json.exists():
            config = json.loads(claude_json.read_text())
        else:
            config = {}

        resolved = str(directory.resolve())
        projects = config.setdefault("projects", {})
        if resolved not in projects:
            projects[resolved] = {}
        projects[resolved]["hasTrustDialogAccepted"] = True

        claude_json.write_text(json.dumps(config, indent=2) + "\n")
        logger.debug(f"Trusted directory in Claude config: {resolved}")
    except Exception as e:
        logger.warning(f"Failed to pre-trust directory {directory}: {e}")


def _setup_artifact_exclusions(repo_path: str, worktree_path: Path) -> None:
    """Configure per-worktree git exclude so artifacts are invisible to git.

    Uses extensions.worktreeConfig + core.excludesFile to scope exclusions
    to this worktree only — the parent repo checkout and other worktrees
    (including other worktrees) are not affected.
    """
    cwd = str(worktree_path)
    try:
        # Enable per-worktree config on the parent repo (idempotent)
        subprocess.run(
            ["git", "config", "extensions.worktreeConfig", "true"],
            cwd=repo_path,
            capture_output=True,
            timeout=5,
        )

        # Resolve this worktree's GIT_DIR
        result = subprocess.run(
            ["git", "rev-parse", "--git-dir"],
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode != 0:
            logger.warning("Could not resolve GIT_DIR for artifact exclusions")
            return

        git_dir = Path(result.stdout.strip())
        if not git_dir.is_absolute():
            git_dir = worktree_path / git_dir

        exclude_dir = git_dir / "info"
        exclude_dir.mkdir(parents=True, exist_ok=True)
        exclude_file = exclude_dir / "gate-exclude"
        exclude_file.write_text(GATE_EXCLUDE_PATTERNS)

        # Set per-worktree core.excludesFile so git add -A ignores artifacts
        subprocess.run(
            ["git", "config", "--worktree", "core.excludesFile", str(exclude_file)],
            cwd=cwd,
            capture_output=True,
            timeout=5,
        )
        logger.debug(f"Artifact exclusions configured: {exclude_file}")
    except Exception as e:
        logger.warning(f"Failed to set up artifact exclusions: {e}")


def prepare_context_files(worktree_path: Path, config: dict | None = None) -> None:
    """Generate diff, changed files, stats, etc. for the review stages.

    These files are consumed by prompt.build_vars() to assemble stage prompts.
    Replaces the shell commands in the GHA workflow's "Setup workspace" step.
    """
    cwd = str(worktree_path)
    default_branch = (config or {}).get("repo", {}).get("default_branch", "main")
    diff_ref = f"origin/{default_branch}...HEAD"

    result = subprocess.run(
        ["git", "diff", diff_ref],
        capture_output=True,
        text=True,
        cwd=cwd,
    )
    (worktree_path / "diff.txt").write_text(result.stdout)

    result = subprocess.run(
        ["git", "diff", "--name-only", diff_ref],
        capture_output=True,
        text=True,
        cwd=cwd,
    )
    changed_files = result.stdout
    (worktree_path / "changed_files.txt").write_text(changed_files)

    file_count = len([f for f in changed_files.strip().split("\n") if f.strip()])
    (worktree_path / "file_count.txt").write_text(str(file_count))

    result = subprocess.run(
        ["git", "diff", "--stat", diff_ref],
        capture_output=True,
        text=True,
        cwd=cwd,
    )
    diff_stats = result.stdout
    (worktree_path / "diff_stats.txt").write_text(diff_stats)

    # lines_changed.txt — last line of diff --stat
    stat_lines = diff_stats.strip().split("\n")
    lines_changed = stat_lines[-1] if stat_lines else "0"
    (worktree_path / "lines_changed.txt").write_text(lines_changed)

    logger.info(
        f"Context files prepared: {file_count} files changed, "
        f"diff={len((worktree_path / 'diff.txt').read_bytes())} bytes"
    )


def create_auxiliary_worktree(
    repo_path: str,
    branch: str,
    base_sha: str,
    label: str = "aux",
    config: dict | None = None,
) -> Path:
    """Create a lightweight worktree for non-review uses (e.g. spec-PR
    promotion in Phase 5).

    Unlike :func:`create_worktree` this does NOT install dependencies,
    prepare context files, or trust-register the directory with
    Claude — it is purely a writable checkout of ``base_sha`` on a new
    branch ``branch`` from ``repo_path``. Author identity is still set
    to the bot so commits attribute correctly.

    ``config`` is the resolved repo config dict; if omitted we fall back
    to ``load_config()`` (kept only as a convenience for ad-hoc callers).
    Pass it explicitly from orchestrator-side callers so the function is
    testable without monkeypatching at the module level.

    Returns the worktree path. Callers MUST call
    :func:`remove_worktree` when done.
    """
    cfg = config if config is not None else load_config()
    repo_cfg = cfg.get("repo", {})
    worktree_base = repo_cfg.get("worktree_base", "/tmp/gate-worktrees")
    unique = f"{int(time.time() * 1000)}-{secrets.token_hex(3)}"
    worktree_path = Path(worktree_base) / f"{label}-{unique}"
    resolved_repo = str(Path(repo_path).expanduser())

    subprocess.run(
        [
            "git", "worktree", "add",
            "-b", branch,
            str(worktree_path), base_sha,
        ],
        cwd=resolved_repo,
        check=True,
        capture_output=True,
        timeout=30,
        env=_git_env(),
    )

    bot = repo_cfg.get("bot_account", "gate-bot")
    for key, val in [
        ("user.name", bot),
        ("user.email", f"{bot}@users.noreply.github.com"),
    ]:
        subprocess.run(
            ["git", "config", key, val],
            cwd=str(worktree_path),
            capture_output=True,
            timeout=10,
        )
    return worktree_path


def remove_worktree(worktree_path: Path) -> None:
    """Remove a worktree and its directory."""
    logger.info(f"Removing worktree: {worktree_path}")
    subprocess.run(
        ["git", "worktree", "remove", "--force", str(worktree_path)],
        capture_output=True,
    )
    if worktree_path.exists():
        shutil.rmtree(worktree_path, ignore_errors=True)


def prune_worktrees(repo_path: str) -> None:
    """Prune stale worktree references."""
    resolved_repo = str(Path(repo_path).expanduser())
    subprocess.run(["git", "worktree", "prune"], cwd=resolved_repo, capture_output=True)
