"""Git worktree management for isolated PR reviews.

Handles worktree creation, context file preparation (diff, changed_files, etc.),
dependency installation, and cleanup.
"""

import base64
import json
import logging
import os
import shutil
import subprocess
import time
from pathlib import Path

from gate.config import gate_dir, load_config, repo_slug

logger = logging.getLogger(__name__)

# Patterns for Gate review/fix artifacts that must never be committed to the
# target repo.  Written to a per-worktree git exclude file by
# _setup_artifact_exclusions() so that `git add -A` ignores them.
#
# Keep in sync with GATE_ARTIFACT_FILES / GATE_ARTIFACT_GLOBS in gate/fixer.py.
GATE_EXCLUDE_PATTERNS = """\
# Gate review/fix artifacts — do not commit
# Auto-generated by workspace._setup_artifact_exclusions()
diff.txt
changed_files.txt
file_count.txt
diff_stats.txt
lines_changed.txt
pr-metadata.json
prior-review.json
build.json
triage.json
architecture.json
security.json
logic.json
verdict.json
fix-build.json
fix-diff.txt
fix-env.json
fix-resume-prompt.md
fix-rereview.json
no-codex.txt
fix.json
*-findings.json
*-result.json
*-session-id.txt
*-raw.json
*.in.md
*.out.md
*.in.md.tmp
fix-build/
"""


def _b64_token(pat: str) -> str:
    return base64.b64encode(f"x-access-token:{pat}".encode()).decode()


def _git_env() -> dict[str, str]:
    """Build env for git commands with explicit HTTPS auth for private repos."""
    env = os.environ.copy()
    pat = os.environ.get("GATE_PAT", "")
    if pat:
        env["GIT_ASKPASS"] = "/bin/echo"
        env["GIT_TERMINAL_PROMPT"] = "0"
        env["GIT_CONFIG_COUNT"] = "1"
        env["GIT_CONFIG_KEY_0"] = "http.https://github.com/.extraheader"
        env["GIT_CONFIG_VALUE_0"] = f"Authorization: Basic {_b64_token(pat)}"
    return env


def _git_fetch_with_retry(repo_path: str, branch: str, max_retries: int = 3) -> None:
    """Fetch with retry and explicit auth."""
    env = _git_env()
    for attempt in range(1, max_retries + 1):
        try:
            subprocess.run(
                ["git", "fetch", "origin", branch],
                cwd=repo_path,
                check=True,
                capture_output=True,
                timeout=90,
                env=env,
            )
            return
        except (subprocess.TimeoutExpired, subprocess.CalledProcessError) as e:
            if attempt < max_retries:
                logger.warning(f"git fetch retry {attempt}/{max_retries}: {e}")
                time.sleep(5 * attempt)
                continue
            raise


def _npm_install_with_retry(worktree_path: Path, max_retries: int = 2) -> None:
    """Run npm ci with retry logic."""
    env = os.environ.copy()
    env["npm_config_cache"] = str(gate_dir() / "npm-cache")
    for attempt in range(1, max_retries + 1):
        try:
            subprocess.run(
                ["npm", "ci"],
                cwd=str(worktree_path),
                check=True,
                capture_output=True,
                timeout=300,
                env=env,
            )
            return
        except (subprocess.TimeoutExpired, subprocess.CalledProcessError) as e:
            if attempt < max_retries:
                logger.warning(f"npm ci retry {attempt}/{max_retries}: {e}")
                time.sleep(10)
                continue
            raise


def create_worktree(
    repo_path: str,
    pr_number: int,
    head_sha: str,
    branch: str,
    repo: str = "",
    config: dict | None = None,
) -> Path:
    """Create an isolated worktree for a PR review.

    Steps:
    1. git fetch origin <branch>
    2. git worktree add /tmp/gate-worktrees/pr<N>-<timestamp> <sha>
    3. Prepare context files (diff, changed_files, etc.)
    4. Run npm ci

    Args:
        repo_path: Path to the main repository clone.
        pr_number: PR number.
        head_sha: Head commit SHA to check out.
        branch: PR branch name.
        repo: GitHub owner/repo string for multi-repo support.
        config: Resolved config dict (avoids re-loading and ensures per-repo values).

    Returns:
        Path to the created worktree.
    """
    config = config or load_config()
    repo_cfg = config.get("repo", {})
    worktree_base = repo_cfg.get("worktree_base", "/tmp/gate-worktrees")
    slug = repo_slug(repo) if repo else ""
    if slug:
        worktree_path = Path(worktree_base) / f"{slug}-pr{pr_number}-{int(time.time())}"
    else:
        worktree_path = Path(worktree_base) / f"pr{pr_number}-{int(time.time())}"

    resolved_repo = str(Path(repo_path).expanduser())

    # Fetch the PR branch with explicit auth and retry
    logger.info(f"Fetching branch {branch} for PR #{pr_number}")
    _git_fetch_with_retry(resolved_repo, branch)

    # Create worktree at the specific SHA (also needs auth env for private repos)
    logger.info(f"Creating worktree at {worktree_path}")
    subprocess.run(
        ["git", "worktree", "add", str(worktree_path), head_sha],
        cwd=resolved_repo,
        check=True,
        capture_output=True,
        timeout=30,
        env=_git_env(),
    )

    # Checkout the PR branch so git push works (worktree add creates detached HEAD)
    subprocess.run(
        ["git", "checkout", "-B", branch, "HEAD"],
        cwd=str(worktree_path),
        check=True,
        capture_output=True,
        timeout=10,
    )

    # Set bot identity for fix pipeline commits
    bot = repo_cfg.get("bot_account", "gate-bot")
    for key, val in [("user.name", bot), ("user.email", f"{bot}@users.noreply.github.com")]:
        subprocess.run(
            ["git", "config", key, val],
            cwd=str(worktree_path),
            capture_output=True,
        )

    # Remove .claude/ from worktree so Claude inherits trust from parent
    claude_dir = worktree_path / ".claude"
    if claude_dir.is_dir():
        shutil.rmtree(claude_dir, ignore_errors=True)

    # Pre-trust the worktree path in Claude's config
    _trust_directory(worktree_path)

    # Prevent Gate artifacts from being staged by git add -A
    _setup_artifact_exclusions(resolved_repo, worktree_path)

    prepare_context_files(worktree_path, config=config)

    # Install dependencies with retry
    logger.info(f"Running npm ci in {worktree_path}")
    _npm_install_with_retry(worktree_path)

    return worktree_path


def _trust_directory(directory: Path) -> None:
    """Register a directory as trusted in Claude Code's config.

    Claude Code stores per-project trust in ~/.claude.json under
    projects.<path>.hasTrustDialogAccepted. Without this, Claude
    shows an interactive "trust this folder" prompt that blocks
    automated agent stages.
    """
    claude_json = Path.home() / ".claude.json"
    try:
        if claude_json.exists():
            config = json.loads(claude_json.read_text())
        else:
            config = {}

        resolved = str(directory.resolve())
        projects = config.setdefault("projects", {})
        if resolved not in projects:
            projects[resolved] = {}
        projects[resolved]["hasTrustDialogAccepted"] = True

        claude_json.write_text(json.dumps(config, indent=2) + "\n")
        logger.debug(f"Trusted directory in Claude config: {resolved}")
    except Exception as e:
        logger.warning(f"Failed to pre-trust directory {directory}: {e}")


def _setup_artifact_exclusions(repo_path: str, worktree_path: Path) -> None:
    """Configure per-worktree git exclude so artifacts are invisible to git.

    Uses extensions.worktreeConfig + core.excludesFile to scope exclusions
    to this worktree only — the parent repo checkout and other worktrees
    (including other worktrees) are not affected.
    """
    cwd = str(worktree_path)
    try:
        # Enable per-worktree config on the parent repo (idempotent)
        subprocess.run(
            ["git", "config", "extensions.worktreeConfig", "true"],
            cwd=repo_path,
            capture_output=True,
            timeout=5,
        )

        # Resolve this worktree's GIT_DIR
        result = subprocess.run(
            ["git", "rev-parse", "--git-dir"],
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode != 0:
            logger.warning("Could not resolve GIT_DIR for artifact exclusions")
            return

        git_dir = Path(result.stdout.strip())
        if not git_dir.is_absolute():
            git_dir = worktree_path / git_dir

        exclude_dir = git_dir / "info"
        exclude_dir.mkdir(parents=True, exist_ok=True)
        exclude_file = exclude_dir / "gate-exclude"
        exclude_file.write_text(GATE_EXCLUDE_PATTERNS)

        # Set per-worktree core.excludesFile so git add -A ignores artifacts
        subprocess.run(
            ["git", "config", "--worktree", "core.excludesFile", str(exclude_file)],
            cwd=cwd,
            capture_output=True,
            timeout=5,
        )
        logger.debug(f"Artifact exclusions configured: {exclude_file}")
    except Exception as e:
        logger.warning(f"Failed to set up artifact exclusions: {e}")


def prepare_context_files(worktree_path: Path, config: dict | None = None) -> None:
    """Generate diff, changed files, stats, etc. for the review stages.

    These files are consumed by prompt.build_vars() to assemble stage prompts.
    Replaces the shell commands in the GHA workflow's "Setup workspace" step.
    """
    cwd = str(worktree_path)
    default_branch = (config or {}).get("repo", {}).get("default_branch", "main")
    diff_ref = f"origin/{default_branch}...HEAD"

    result = subprocess.run(
        ["git", "diff", diff_ref],
        capture_output=True,
        text=True,
        cwd=cwd,
    )
    (worktree_path / "diff.txt").write_text(result.stdout)

    result = subprocess.run(
        ["git", "diff", "--name-only", diff_ref],
        capture_output=True,
        text=True,
        cwd=cwd,
    )
    changed_files = result.stdout
    (worktree_path / "changed_files.txt").write_text(changed_files)

    file_count = len([f for f in changed_files.strip().split("\n") if f.strip()])
    (worktree_path / "file_count.txt").write_text(str(file_count))

    result = subprocess.run(
        ["git", "diff", "--stat", diff_ref],
        capture_output=True,
        text=True,
        cwd=cwd,
    )
    diff_stats = result.stdout
    (worktree_path / "diff_stats.txt").write_text(diff_stats)

    # lines_changed.txt — last line of diff --stat
    stat_lines = diff_stats.strip().split("\n")
    lines_changed = stat_lines[-1] if stat_lines else "0"
    (worktree_path / "lines_changed.txt").write_text(lines_changed)

    logger.info(
        f"Context files prepared: {file_count} files changed, "
        f"diff={len((worktree_path / 'diff.txt').read_bytes())} bytes"
    )


def remove_worktree(worktree_path: Path) -> None:
    """Remove a worktree and its directory."""
    logger.info(f"Removing worktree: {worktree_path}")
    subprocess.run(
        ["git", "worktree", "remove", "--force", str(worktree_path)],
        capture_output=True,
    )
    if worktree_path.exists():
        shutil.rmtree(worktree_path, ignore_errors=True)


def prune_worktrees(repo_path: str) -> None:
    """Prune stale worktree references."""
    resolved_repo = str(Path(repo_path).expanduser())
    subprocess.run(["git", "worktree", "prune"], cwd=resolved_repo, capture_output=True)
